config/routes.rb
EsteticaNegrete::Application.routes.draw do
  resources :esteticas

  root :to => 'esteticas#index'
  get '/google470612d70cfe2ed0', :to => 'esteticas#google'
  get '/contact', :to => 'esteticas#contact', :as => 'contact'

  post '/send_contact', :to => 'esteticas#send_mail', :as => 'send_contact'
  match '/map', :to => 'esteticas#map', :as => 'map'
  get '/who_we_are', :to => 'esteticas#who_we_are', :as => 'who_we_are'
  get '/:content', :to => 'esteticas#content', :as => 'content'

  

end

app/models/contact_email.rb
class ContactEmail < ActiveRecord::Base
  attr_accessible :comment, :email, :name

  def create_contact(params)
  	self.name = params["name"]
  	self.email = params["email"]
  	self.comment = params["comment"]
  	self.save!
  end
end

app/models/estetica.rb
class Estetica < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/map.rb
class Map < ActiveRecord::Base
  acts_as_gmappable
  
  attr_accessible :address, :city, :country, :gmaps, :latitude, :longitude, :name

  # validates :address, :presence => true
  # validates :city, :presence => true
  # validates :country :presence => true

  def self.set_map
    if Map.all.count == 0
      map = Map.new
    	map.name = APP_CONFIG['map']['name']
    	map.address = APP_CONFIG['map']['address']
    	map.city = APP_CONFIG['map']['city']
    	map.country = APP_CONFIG['map']['country']
    	map.latitude = APP_CONFIG['map']['latitude'].to_f
    	map.longitude = APP_CONFIG['map']['longitude'].to_f
    	map.gmaps = true
    	map.save!
    else
      map = Map.first
      map.save!
    end
    return map
  end

  def gmaps4rails_address
  	"#{self.address}, #{self.city}, #{self.country}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/esteticas_controller.rb
class EsteticasController < ApplicationController
  # GET /esteticas
  # GET /esteticas.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @esteticas }
    end
  end

  def google
    render 'google470612d70cfe2ed0', :layout => false
  end

  def content
    render "#{params[:content]}"
  end

  def contact
    
  end

  def send_mail
    contact = ContactEmail.new
    begin
      contact.create_contact(params) 
      UserMailer.send_contact_email(contact).deliver
      redirect_to root_path, :notice => "Se ha enviado el correo."
    rescue Exception => e
      redirect_to contact_path, :error => "No se ha podido enviar el correo."
    end
  end

  def map
    map = Map::set_map
    logger.debug { "#{map.inspect}" }
    @json = map.to_gmaps4rails
    logger.debug { "\n#{@json.inspect}"}
  end
  
  def get_address
  end

  # GET /esteticas/1
  # GET /esteticas/1.json
  def show
    @estetica = Estetica.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @estetica }
    end
  end

  # GET /esteticas/new
  # GET /esteticas/new.json
  def new
    @estetica = Estetica.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @estetica }
    end
  end

  # GET /esteticas/1/edit
  def edit
    @estetica = Estetica.find(params[:id])
  end

  # POST /esteticas
  # POST /esteticas.json
  def create
    @estetica = Estetica.new(params[:estetica])

    respond_to do |format|
      if @estetica.save
        format.html { redirect_to @estetica, notice: 'Estetica was successfully created.' }
        format.json { render json: @estetica, status: :created, location: @estetica }
      else
        format.html { render action: "new" }
        format.json { render json: @estetica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /esteticas/1
  # PUT /esteticas/1.json
  def update
    @estetica = Estetica.find(params[:id])

    respond_to do |format|
      if @estetica.update_attributes(params[:estetica])
        format.html { redirect_to @estetica, notice: 'Estetica was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @estetica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /esteticas/1
  # DELETE /esteticas/1.json
  def destroy
    @estetica = Estetica.find(params[:id])
    @estetica.destroy

    respond_to do |format|
      format.html { redirect_to esteticas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/esteticas_helper.rb
module EsteticasHelper
end

app/views/esteticas/_contact_form.html.erb
<%= form_tag(send_contact_path, :class => "form-horizontal") do %>
    <div class="control-group">
        <%= label_tag "name", "Nombre", :class => "control-label"%>
        <div class="controls">
            <%= text_field_tag "name", "" %>
        </div>
    </div>
    <div class="control-group">
        <%= label_tag "email", "Correo", :class => "control-label"%>
        <div class="controls">
            <%= text_field_tag "email", "", :type => "email"  %>
        </div>
    </div>
    <div class="control-group">
        <%= label_tag "comment", "Comentario", :class => "control-label"%>
        <div class="controls">
            <%= text_area_tag "comment", "", :size => "25x5"  %>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn">Enviar</button>
        </div>
    </div>
 <% end -%> 

app/views/esteticas/_form.html.erb
<%= form_for(@estetica) do |f| %>
  <% if @estetica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estetica.errors.count, "error") %> prohibited this estetica from being saved:</h2>

      <ul>
      <% @estetica.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/esteticas/acido_hialuronico.html.erb
<legend>Ácido Hialurónico</legend>
<div class="row-fluid">
	<div class="span12">
		<p>
			Es una molécula presente en los organismos vivos, que con el paso de los años se va perdiendo;
			tiene la capacidad de retener agua por lo que se utiliza para devolver volúmenes perdidos e
			hidratar la piel.
		</p>
		<p>
			Es un procedimiento muy solicitado por personas que quieren cambiar su aspecto, suavizar la piel, definir labios y quitar arrugas. 
		</p>
	</div>
</div>
<div class="row-fluid">
	<div class="span8 offset2">
		<div class="row-fluid">
			<div class="span6" style="text-align:center;">
				<h4>Antes</h4>
    			<%= image_tag('antes.jpg', :class => 'img-rounded')%>
			</div>
			<div class="span6" style="text-align:center;">
				<h4>Después</h4>
    			<%= image_tag('despues.jpg', :class => 'img-rounded')%>
			</div>
		</div>
	</div>
</div>

app/views/esteticas/contact.html.erb
<legend>Contáctanos</legend>
<p>Si necesitas reservar horas o resolver cualquier inquietud, envíanos un correo a través de este formulario.</p>
<%= render :partial => 'contact_form' %>

app/views/esteticas/edit.html.erb
<h1>Editing estetica</h1>

<%= render 'form' %>

<%= link_to 'Show', @estetica %> |
<%= link_to 'Back', esteticas_path %>

app/views/esteticas/index.html.erb
<script type="text/javascript">
  $(window).load(function() {
    $('.flexslider').flexslider({
      animation: "slide",
      slideshowSpeed: 5000,
    });
  });
</script>

<div>
  <div >
    <p style="font-size:16px">
      En nuestra clínica, nos preocupamos por un concepto de belleza integral, entregando múltiples opciones desde donde podemos mejorar la imagen del rostro, ofreciendo una alternativa única según la ﬁsonomía de cada paciente.
    </p>
    <p style="font-size:16px">
      Para nuestros tratamientos utilizamos solo productos que cumplan con los mas altos estándares de calidad y nuestros profesionales son altamente caliﬁcados y certiﬁcados.
    </p><!-- 
    <p style="font-size:16px; text-align:center;">
      Venga a conocernos y...
    </p> -->
    <p style="font-size:18px;text-align:center;margin:30px 0">
      ¡VENGA A CONOCERNOS Y  DESE UN GUSTO!
    </p>
  </div>
  <div class="slider-container">
    <%= render :partial => "/layouts/slider" %>
  </div>
</div>

app/views/esteticas/map.html.erb
<div class="row-fluid">
	<legend>Encuentranos Aquí</legend>
	<div class="span6">
		<p></p>
		<%= gmaps(
			:map_options => {
				:raw => "{scrollwheel: false}",
				"auto_zoom" => false,
				"zoom" => 17,
				"scrollwheel" => false,
				"zoom_control" => true,
				"zoom_control_opt" => {
					"style" => "SMALL",
					"position" => "TOP_LEFT" 
				},
				"panControl" => true,
		        "street_view_control" => false,
		        "map_type_control" => false,
		        "overview_map_control" => false
		    }, 
			:markers => { "data" => @json, "options" =>{
				"picture" => "assets/logo_marker.png",
				"width" => 50,
				"length" => 50
			}}) %>
	</div>
</div>

app/views/esteticas/new.html.erb
<h1>New estetica</h1>

<%= render 'form' %>

<%= link_to 'Back', esteticas_path %>

app/views/esteticas/prp.html.erb
<legend>Plasma Rico en Plaquetas <i>(PRP)</i></legend>
<div class="row-fluid">
	<div class="span6">
		<p>
			El plasma rico en plaquetas, es un tratamiento que consiste en extraer un concentrado de
			plaquetas a partir de la sangre de cada paciente, la que es procesada y centrifugada en el mismo
			momento, para obtener un agente antienvejecimiento único y natural para cada paciente.
		</p>
		<p>
			Su efecto biológico se basa en la estimulación del ﬁbroblasto, célula encargada de la formación del
			colageno, el cual se va perdiendo en la medida en que envejecemos, de esta manera se sintetiza
			una mayor matriz colagena, devolviendo la estructura y aspecto juvenil a la piel.
		</p>
		<p>
			<strong>¿Cuándo se recomienda la aplicación del PRP?</strong>
			<ul>
				<li>
					A partir de los 30 años (de manera preventiva). 
				</li>
				<li>
					Signos de envejecimiento prematuro.			
				</li>
				<li>
					Pieles envejecidas.
				</li>
			</ul>
		</p>
	</div>
	<div class="span6">
		<div class="row-fluid">
			<div class="span7 offset2">
    			<%= image_tag('prp.jpg', :class => 'img-rounded')%>
			</div>
		</div>
	</div>
</div>

app/views/esteticas/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_estetica_path(@estetica) %> |
<%= link_to 'Back', esteticas_path %>

app/views/esteticas/soft_lift.html.erb
<legend>Soft Lift</legend>
<div class="row-fluid">
	<div class="span6">
		<p>
			Tratamiento combinado que consiste en mezclar las cualidades del Ácido Hialurónico y la toxina Botulínica tipo A, para tratar el rostro en forma integral, manejando los 3 tercios de la cara, generando una apariencia bien balanceada y alta satisfacción del paciente; ademas, es un procedimiento mínimamente invasivo, que permite retrasar un eventual procedimiento quirúrgico.
		</p>
	</div>
	<div class="span6">
		<div class="row-fluid">
				<div class="span7 offset2">
	    			<%= image_tag('botox.jpg', :class => 'img-rounded')%>
				</div>
			</div>
		</div>
</div>

app/views/esteticas/toxina_butolinica.html.erb
<legend>Toxina Butolínica</legend>
<div class="row-fluid">
	<div class="span6">
		<p>
			La toxina Botulínica disminuye la contracción del músculo, por lo que relaja la musculatura que
			produce surcos y/o pliegues dejando descansar a la piel, eliminando de esta forma rápida y
			efectivamente las expresiones no deseadas.
		</p>
		<p>
			El procedimiento es muy rápido, dura menos de una hora, no requiere de preparación previa ni anestesias. Su efecto es prolongado y va desapareciendo paulatinamente, logrando un resultado muy natural.
		</p>
	</div>
	<div class="span6">
		<div class="row-fluid">
				<div class="span7 offset2">
	    			<%= image_tag('botox.jpg', :class => 'img-rounded')%>
				</div>
			</div>
		</div>
</div>

app/views/esteticas/who_we_are.html.erb
<legend>Quiénes Somos</legend>
<div class="row-fluid">
	<div class="span12">
		<p>
			Dése un gusto, nace como respuesta a una creciente tendencia mundial que llega a Chile, en la que población de mediana edad quiere mantener un aspecto juvenil por más tiempo y/o retardar los signos tempranos del envejecimiento.
		</p>
		<p>
			Los profesionales que prestan servicios, pueden ser Médicos u Odontólogos avalados por el código sanitario Articulo 115, quienes han obtenido sus certiﬁcados de especialistas en Rejuvenecimiento Facial y ademas están registrados en la Sociedad de estética Maxilofacial, entidad que vela por el interés cientíﬁco y buen ejercicio de esta profesión.			
		</p>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="container">
		<div class="row-fluid">
			<div class="span4 siguenos">
				<legend>SÍGUENOS</legend>
				<p>También puedes darte un gusto siguiendonos en nuestras redes sociales.</p>
				<br>
				<div class="social_net">
					<a class="red_social facebook" href="https://www.facebook.com/DeseUnGusto" target="_blank"></a>
					<a class="red_social twitter" href="https://twitter.com/deseungusto" target="_blank"></a>
					<a class="red_social forsquare" href="#"></a>
				</div>
			</div>
			<div class="span4 encuentranos">
				<legend>NOS ENCONTRAMOS EN</legend>
				<p>
					Para mayor información acerca del rejuvenecimiento facial, te invitamos a visitar nuestra clínica y contactarnos:
				</p>
				<ul>
				    <li>Torres Flamenco (<a href=<%= map_url%>>Ver mapa</a>) Oficina 403</li>
				    <li>Fono: (52) 21 37 20</li>
				</ul>
			</div>
			<div class="span4 recomendamos">
				<legend>TE RECOMENDAMOS</legend>
				<p>
					Para que te informes más y conozcas a nuestros asociados, te invitamos a visitar los siguientes sitios:
				</p>
				<ul>
				    <li>
				    	<a href="http://www.sociedadesteticamaxilofacial.cl/" target="_blank">Sociedad Chilena de Estética Maxilofacial</a>
				    </li>
				    <li>
				    	<a href="www.centrosanfrancisco.cl ">Centro San Francisco</a>
				    </li>
				    <li>
				    	<a href="www.moren.cl">Dra. Carmen Moren</a>
				    </li>
				</ul>
			</div>
		</div>
	</div>
</div>
<%= yield :scripts %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_slider.html.erb
<div class="flexslider">
  <ul class="slides">
    <li>
      <%= image_tag('slider/acido_hialuronico.jpg', :style => "text-align:center")%>
      <h4 class="flex-caption" style="margin-left:5px; text-align:center; color:white">Ácido Hialurónico</h4>
    </li>
    <li>
      <%= image_tag('slider/botox.jpg', :style => "text-align:center")%>
      <h4 class="flex-caption" style="margin-left:5px; text-align:center; color:white">Toxina Butolínica</h4>
    </li>
    <li>
      <%= image_tag('slider/prp.jpg', :style => "text-align:center")%>
      <h4 class="flex-caption" style="margin-left:5px; text-align:center; color:white">Plasma Rico en Plaquetas</h4>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeseUnGusto</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag "flexslider", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.flexslider.js" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="head-banner span12">
        <%= image_tag('banner.jpg')%>
      </div>
    </div>
    <br>
    <div class="row">
      <%= render :partial => "/layouts/messages" %>
    </div>
    <br>
    <div class="row yield">
      <div class="span3 menu">
        <ul id="menu-lateral" class="nav nav-list">
          <li class="home" ><a href=<%= root_url %>>Home</a></li>
          <li class="who_we_are"><a href=<%= who_we_are_url %>>Quiénes somos</a></li>
          <li class="nav-header">Te ofrecemos</li>
          <li class="prp"><a href=<%= content_url(:content => 'prp')  %>>Plasma Rico en Plaquetas</a></li>
          <li class="acido_hialuronico"><a href=<%= content_url(:content => 'acido_hialuronico') %>>Ácido Hialurónico</a></li>
          <li class="toxina_butolinica"><a href=<%= content_url(:content => 'toxina_butolinica')  %>>Toxina Butolínica</a></li>
          <li class="soft_lift"><a href=<%= content_url(:content => 'soft_lift') %>>Soft Lift</a></li>
          <li class="divider"></li>
          <li class="contact"><a href= <%= contact_url %>>Contáctanos</a></li>
          <li class="map"> <a href= <%= map_url %>>Mapa</a></li>
        </ul>
      </div>
      <div class="span9">
        <%= yield %>
      </div>
    </div>
  </div>
<%= render :partial => "/layouts/footer" %>
</body>

</html>